version: "3.9"
services:
  # docker-compose run --rm speaker
  speaker:
    image: amd64/alpine
    container_name: speaker
    build:
      context: .
      dockerfile: ./docker/speaker.dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - "/dev/input:/dev/input:ro"
      - "/run/udev:/run/udev:ro"
    privileged: true
    cap_add:
      - SYS_ADMIN
    #devices:
    #tmpfs:
      #- "/dev"
    network_mode: "host"
    environment:
      UDEV: 1
      DISPLAY: $DISPLAY
